#pragma once

#include <cstdint>

enum ScreenId : uint8_t
{
    ScreenMenu = 0,
    ScreenDebug = 1,
    ScreenRotate = 2,
    ScreenClip = 3,
    ScreenAdapt = 4,
    ScreenFonts = 5,
    ScreenWeight = 6,
    ScreenStyles = 7,
    ScreenText = 8,
    ScreenTextbox = 9,
    ScreenMarquee = 10,
    ScreenIcons = 11,
    ScreenAnimIcons = 12,
    ScreenLines = 13,
    ScreenFillRect = 14,
    ScreenStrokeRect = 15,
    ScreenCircle = 16,
    ScreenLight = 17,
    ScreenEllipse = 18,
    ScreenTri = 19,
    ScreenVerts = 20,
    ScreenRoundTri = 21,
    ScreenRoundVerts = 22,
    ScreenArc = 23,
    ScreenSquFill = 24,
    ScreenSquLine = 25,
    ScreenGradV = 26,
    ScreenGradH = 27,
    ScreenGradD = 28,
    ScreenGradC = 29,
    ScreenGradR = 30,
    ScreenBlur = 31,
    ScreenBlurDir = 32,
    ScreenBlurUp = 33,
    ScreenBlurDUp = 34,
    ScreenGlow = 35,
    ScreenGlowUp = 36,
    ScreenDots = 37,
    ScreenDots7 = 38,
    ScreenDotsMany = 39,
    ScreenButton = 40,
    ScreenButtonUp = 41,
    ScreenToggle = 42,
    ScreenToggleUp = 43,
    ScreenSlider = 44,
    ScreenSliderUp = 45,
    ScreenProgress = 46,
    ScreenProgressUp = 47,
    ScreenCircleProg = 48,
    ScreenCircleProgUp = 49,
    ScreenDrumH = 50,
    ScreenDrumV = 51,
    ScreenListPlain = 52,
    ScreenTileA = 53,
    ScreenTileB = 54,
    ScreenTileCustom = 55,
    ScreenGraphDraw = 56,
    ScreenGraphUpdate = 57,
    ScreenGraphScope = 58,
    ScreenGraphLine = 59,
    ScreenToast = 60,
    ScreenNotifA = 61,
    ScreenNotifB = 62,
    ScreenPopupA = 63,
    ScreenPopupB = 64,
    ScreenErrWarn = 65,
    ScreenErrCrash = 66,
    ScreenShotA = 67,
    ScreenShotB = 68,
    ScreenWifi = 69,
    ScreenOta = 70
};
