SCREEN(menu, ScreenMenu)
{
    (void)ui.listNav();
    ui.updateList()
        .items(
            listItem(arrow, "Runtime", "Tile/fullscreen, debug overlays, screenshot mode", ScreenDebug),
            listItem(checkmark, "Rotate", "Runtime screen rotation API and animated transitions", ScreenRotate),
            listItem(warning, "Clip", "setClip() with warning/error layers", ScreenClip),
            listItem(checkmark, "Light", "Brightness, max brightness and backlight policy", ScreenLight),
            listItem(checkmark, "Adapt", "Adaptive preview shrinks on enter and restores on exit", ScreenAdapt),
            listItem(arrow, "Fonts", "WixMadeForDisplay vs KronaOne by size", ScreenFonts),
            listItem(checkmark, "Weight", "Font weight matrix for both PSDF fonts", ScreenWeight),
            listItem(arrow, "Styles", "H1, H2, Body, Caption", ScreenStyles),
            listItem(checkmark, "Text", "drawText() and updateText() positions", ScreenText),
            listItem(arrow, "Textbox", "drawTextBox() sizes, align, lineGap", ScreenTextbox),
            listItem(warning, "Marquee", "drawTextMarquee() and drawTextEllipsized()", ScreenMarquee),
            listItem(checkmark, "Icons", "All icon glyphs, colors and layered battery", ScreenIcons),
            listItem(arrow, "Anim", "drawAnimIcon() and updateAnimIcon()", ScreenAnimIcons),
            listItem(checkmark, "Lines", "drawLine() thickness, direction, placement", ScreenLines),
            listItem(arrow, "FillRect", "Filled rects: single and per-corner radii", ScreenFillRect),
            listItem(warning, "StrokeRect", "Border-only rect variants", ScreenStrokeRect),
            listItem(error, "Circle", "Filled vs stroked circles", ScreenCircle),
            listItem(arrow, "Ellipse", "drawEllipse() fill and stroke matrix", ScreenEllipse),
            listItem(checkmark, "Tri", "drawTriangle() isosceles preset directions", ScreenTri),
            listItem(checkmark, "Verts", "drawTriangle() arbitrary vertices", ScreenVerts),
            listItem(checkmark, "RoundTri", "Rounded preset triangles", ScreenRoundTri),
            listItem(checkmark, "RoundVerts", "Rounded vertex triangles", ScreenRoundVerts),
            listItem(arrow, "Arc", "drawArc() angle, radius, thickness, color", ScreenArc),
            listItem(checkmark, "SquFill", "Filled squircle rectangles", ScreenSquFill),
            listItem(checkmark, "SquLine", "Stroked squircle rectangles", ScreenSquLine),
            listItem(arrow, "Grad V", "gradientVertical()", ScreenGradV),
            listItem(arrow, "Grad H", "gradientHorizontal()", ScreenGradH),
            listItem(arrow, "Grad D", "gradientDiagonal()", ScreenGradD),
            listItem(arrow, "Grad C", "gradientCorners()", ScreenGradC),
            listItem(arrow, "Grad R", "gradientRadial()", ScreenGradR),
            listItem(warning, "Blur", "drawBlur() static material", ScreenBlur),
            listItem(warning, "BlurDir", "drawBlur() directional material", ScreenBlurDir),
            listItem(warning, "BlurUp", "updateBlur() moving underlays", ScreenBlurUp),
            listItem(warning, "BlurDUp", "updateBlur() directional moving underlays", ScreenBlurDUp),
            listItem(checkmark, "Glow", "drawGlowCircle() static variants", ScreenGlow),
            listItem(checkmark, "GlowUp", "updateGlowCircle() animated pulse variants", ScreenGlowUp),
            listItem(arrow, "Dots", "drawScrollDots() count/radius/spacing", ScreenDots),
            listItem(arrow, "Dots7", "updateScrollDots() <= 7 controlled", ScreenDots7),
            listItem(arrow, "DotsMany", "updateScrollDots() > 7 controlled", ScreenDotsMany),
            listItem(checkmark, "Button", "drawButton() variants", ScreenButton),
            listItem(checkmark, "ButtonUp", "updateButton() states and progress", ScreenButtonUp),
            listItem(checkmark, "Toggle", "drawToggleSwitch() variants", ScreenToggle),
            listItem(checkmark, "ToggleUp", "updateToggleSwitch() controlled/auto", ScreenToggleUp),
            listItem(arrow, "Slider", "drawSlider() variants", ScreenSlider),
            listItem(arrow, "SliderUp", "updateSlider() controlled/auto", ScreenSliderUp),
            listItem(checkmark, "Progress", "drawProgress() variants", ScreenProgress),
            listItem(checkmark, "ProgressUp", "updateProgress() variants", ScreenProgressUp),
            listItem(checkmark, "CProg", "drawCircleProgress() variants", ScreenCircleProg),
            listItem(checkmark, "CProgUp", "updateCircleProgress() variants", ScreenCircleProgUp),
            listItem(arrow, "Drum H", "drawDrumRoll() horizontal", ScreenDrumH),
            listItem(arrow, "Drum V", "drawDrumRoll() vertical", ScreenDrumV),
            listItem(checkmark, "Plain", "updateList() plain with checked row", ScreenListPlain),
            listItem(checkmark, "Tile A", "updateTile() columns and radius", ScreenTileA),
            listItem(checkmark, "Tile B", "updateTile() alternate mode", ScreenTileB),
            listItem(checkmark, "TileCustom", "Custom tile layout", ScreenTileCustom),
            listItem(arrow, "Graph", "drawGraphGrid() directions and lines", ScreenGraphDraw),
            listItem(arrow, "GraphUp", "updateGraphGrid() live traces", ScreenGraphUpdate),
            listItem(arrow, "Scope", "Oscilloscope graph sample buffer", ScreenGraphScope),
            listItem(arrow, "LineGraph", "drawGraphLine() multi-line feed", ScreenGraphLine),
            listItem(warning, "Toast", "showToast() sequence", ScreenToast),
            listItem(warning, "Notif A", "showNotification() timer/types", ScreenNotifA),
            listItem(warning, "Notif B", "showNotification() buttons/icons", ScreenNotifB),
            listItem(warning, "Popup A", "showPopupMenu() anchored to button", ScreenPopupA),
            listItem(warning, "Popup B", "showPopupMenu() width/count variants", ScreenPopupB),
            listItem(warning, "Warn", "showError() Warning", ScreenErrWarn),
            listItem(error, "Error", "showError() Error", ScreenErrCrash),
            listItem(arrow, "Shot A", "drawScreenshot() grid/count", ScreenShotA),
            listItem(arrow, "Shot B", "drawScreenshot() position/padding", ScreenShotB),
            listItem(checkmark, "WiFi", "Wi-Fi request/state/IP", ScreenWifi),
            listItem(checkmark, "OTA", "OTA check/install/stable-list state", ScreenOta))
        .inactive(panel(ui))
        .active(accent2(ui))
        .mode(Cards);
}
